[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py collectstatic --noinput && python manage.py migrate --noinput && gunicorn config.wsgi --bind 0.0.0.0:$PORT --timeout 120 --access-logfile - --error-logfile - --capture-output --log-level debug"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
